keys:
  - &operator age10gzj30y0wv32y040ymu2k2u76eldtry335zg9rk58d54algtp40sjgmrf4
  - &nix-thinkpad age1zkftm4fhsuv4gscxwqrxp5jfkhr7u63wsxdehhw0w0cd4kutzy9szzrhy9
  - &nix-letsnote1 age1ms8xr24y5yy0s2se255v8vy2s602twyjqwdlswq0jf50f3ty6cjsuczrev
creation_rules:
  - path_regex: secrets/base.yaml
    key_groups:
    - age:
      - *operator
      - *nix-thinkpad
      - *nix-letsnote1