---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    service:
      annotations:
        metallb.io/loadBalancerIPs: ${INGRESS_IP}
        ports:
    ports:
      web:
        asDefault: true
      websecure:
        asDefault: true
      public:
        port: 9443
        exposedPort: 8443
        protocol: TCP
        http:
          tls:
            enabled: true
        proxyProtocol:
          trustedIPs:
            - 10.42.0.0/16
        forwardedHeaders:
          trustedIPs:
            - 10.42.0.0/16
        expose:
          default: false
