---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: lab
  namespace: flux-system
spec:
  interval: 5m0s
  ref:
    branch: master
  timeout: 1m0s
  url: https://github.com/nsc99/lab
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-controllers
  namespace: flux-system
spec:
  interval: 10m0s
  timeout: 1m0s
  path: ./infra/controllers
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: lab
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-configs
  namespace: flux-system
spec:
  interval: 10m0s
  timeout: 1m0s
  path: ./infra/configs
  prune: true
  dependsOn:
    - name: infra-controllers
  sourceRef:
    kind: GitRepository
    name: lab
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 10m0s
  timeout: 1m0s
  path: ./cluster/apps
  prune: true
  sourceRef:
    kind: GitRepository
    name: lab
  decryption:
    provider: sops
    secretRef:
      name: sops-age