apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mokuro-bunko-data
  namespace: mokuro-bunko
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
