apiVersion: v1
kind: Secret
metadata:
    name: cloudflared
    namespace: cloudflared
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:j/K3DHN1+hEYxgCe1vB+keO5ychfqI8SikdC7sJqIdp34KFshS7W+uTxTyBOb9WUAzA1ib65FZR8AoLmmi5nKN/HmpyeAAgQs60rtnUAiCMWECf+fEWp4o/BCn2fowMp88Gn+oDqxMheCi6t+u6b6yEfQq3TI4vpmHe2J9LxKBboZwcz6qoxlHFrCsv8weckRzZaKICLks1BnaXQqhFwU+MPFPqiPLiECtl3EXrv1143xlum6DSq4Q==,iv:iTZ0uS0koV0Bwg7TrtLrbLSBMc074sjt/MPjO00rBUU=,tag:pv6ztz9ihtSQJ9rMVbbgNw==,type:str]
sops:
    age:
        - recipient: age10gzj30y0wv32y040ymu2k2u76eldtry335zg9rk58d54algtp40sjgmrf4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiVllIYjgyMGt6MzAvWnNr
            SlUvYldUdGw3Q2ZpMUQzeFBHZVVnTk1TeDJnCkRWbmFsQjQ1VXZIbDROcGpCWTJW
            TzBOdHI4RCtPSUxOeUp6cGZWaEJWNlUKLS0tIFRjc3g4RXVqaUpCYzVla29CWXp6
            WlE5K2dPSG0zUlZsQTA2K3BSbDBWdDAKVsR4oiX9PwzB92DlYHAFS15plVIaG03S
            BbrbafR73pL6nR3A4j2VKHBoVFYFVIPwqV7Vf3l+X/vqcH69xrHLiw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-14T16:04:01Z"
    mac: ENC[AES256_GCM,data:9tLFl7wEbzKnmDg5qd07fJ1BzltsdIEesyJ+6OIl1llo2PGvngBDmz/dlRrus1xQgzgtBaHjzqicTeBsj2zSSy3or8yLKexjhVb8cfTV66wF7zpVWC1dI5xztpcyEnbE0bTt9jA+QBVC3Qpl1JO2inBWbjPbdpE7fBbx7pcC0U8=,iv:86PpZtygi9FWv/28UHlseFAdvUku6zyeGvuG4MZwKiU=,tag:vTWCPkj03DbXiOHZf4fA+g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
