apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
    namespace: tailscale
type: Opaque
stringData:
    client_id: ENC[AES256_GCM,data:o0NYeKLHovU7ZBCrFBF1T/g=,iv:FstJFLRZ/WpcNUBsQXiAKsbP9+rwZToM62MLcK1rkqw=,tag:EGisrJMKLSk5JwKVF5Hgdw==,type:str]
    client_secret: ENC[AES256_GCM,data:4Q9Vcw+BKIBNIGlyL3mFvtvrvOFo34/WSIDI/BjBRHiP4c/7Mfs1+/VrKL+3kdEjtt7DjNxWjZzdWCpNbeqN1A==,iv:JyJz7dxEmzj7rOMVubMQGe/xVk6oRjNXcb5NT1sY01c=,tag:HEuacVZyhScfYVWm2StAdQ==,type:str]
sops:
    age:
        - recipient: age10gzj30y0wv32y040ymu2k2u76eldtry335zg9rk58d54algtp40sjgmrf4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwVnl6SFlZb2w0WkQxY01y
            UEhDWTA4eUpua1JjSFBkUHo0QjVLNWFHVFUwCnNnKzlENmllbHE0K0IxSndVN3JE
            aFZLS2dNVE5FK1AyeUJLNEFDUWtkRTgKLS0tIG92dVlKSnJKOVRjNnZjaEw1dmFR
            cUV5SjJNNkc0dmtyUWZHMHM5MjlhZmMKobasPO7PdR/zxj+66TgSaOBLfnOQAblC
            MjECI5P7Kb/pUn8rYtT4jlPJlld/qfGS1bBUzQXEyreUzLG65d0NZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-09T15:06:29Z"
    mac: ENC[AES256_GCM,data:aMVLzp+vR7bX3Hj5QbHxEMGM/Mx8VknXzul5rs2SlEkJ3Qz6rbjfQ4YWKLw3FZ1L85Dwgp88QPorhmOsf1ihrTPSlXpzxUgBBWJOyRvFn8ZANydwG9Z0E+/i71XM6IGRXekjcNufeeKABJy6bolcKY3/SknxiWgqhsECgwukOwo=,iv:VlPUCwWHmPL0L6JsLOngMaJiZYEINRX8HX32j63W3pM=,tag:odA+ZojS4MQzhON+3TwQ4w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
