network.env: ENC[AES256_GCM,data:AcMe0twnNhfckFuqI4iDjAJrSSaUaeYBQOMq3yN2GI1kQSmGyNQAWpfjJx+aAONafi9ksQ==,iv:u9YWBE0vR//H3/w8ZkqDqFUVLKFk6zNSM6DxbgYRM4I=,tag:jbqGqFySJxyekCYLp10kUQ==,type:str]
k3s.server.token: ENC[AES256_GCM,data:G4hzdpOymw49GSgLGn3V2gVXL0oGHa9oPI8I0Eip09IgrSsuCkofD3JgnumaaF5R3mkQUxmtHgC7QTeqnYH1Y4pxLkTfO7YpBqqaMLFJL3YCMTRuAwxW+DHYRXuNfU5zNsIVjT2NJbI+PHUFukcb4HgxIr5FUBKg5VfU3SQn6zWnKVVGc532uBPujkD+JTmKtawG0UHKyHOPbdxkIw78F68osAgf/AqYVxQOIwPu7TtS7XNFQJfOUwDeFIy4w5MSL86BnRThrX3PVenzEp5asCL9g9jC+urNIeiN5gccyW3x7SodJBQeOryjUJNt6PUFt+VY8Wgs9AW+i2UAwqTSVAo=,iv:KxRsn3JkGRmR3qHOfRYq8yBy89MtRDlL9KwsGVDLs24=,tag:GSZo1D8jojoX4CVFsSFRyg==,type:str]
k3s.agent.token: ENC[AES256_GCM,data:NfIn7EPapJyqRI//3K1+BXB/W1Uy6emvWJbTd+vYjICajnFVHNJfWXplvltMiEf6/iuRmNigX86febMEDXSLLvSsONIIEBNgxZQ28VkhBDo0qO8Mb/EVO006Ofd9PZFN1uWajBfmv4jF266ZJVk/yt67OsQj6tqM+Dg0O8CuW5qx9oX6NFdrCZwKnzFonNQ0xc3yDQSauJMG5QsqJVz3jdlFqKF1NNMwy9EO6Ylnipl590lxOg5GyGLH9aHMnmU0fTDfCfJAqoGZLn2mc2D9Bdhk0kgwr5CxI+biWDiBcyGjsfTL9F578gbRqOhgLdg4zVXeIdEM1mII5tzbbQBtrdc=,iv:qGTJ/S4gwlXlvzf6UoMDiwePBehjHtWFFfxpf1dErcM=,tag:kfrGgeoB2fWc42snDOY/Yw==,type:str]
sops:
    age:
        - recipient: age10gzj30y0wv32y040ymu2k2u76eldtry335zg9rk58d54algtp40sjgmrf4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArQU1oRzhtc2tvYVNHc0Zo
            TndINUU1enJ2UkVHVDczUk9xaWFZbVM4VkJVCnhMQzlEd1U5c2phNlF6eUdjeXVN
            M1lrQ1g5Q040TW9ycnpTVENqVFcwMncKLS0tIFVIb0NZWHdtRGN6Szl2UEtObEJy
            NGM2WFQ2SEEvS0pidmNZVWxvL0RpaTgK17meUcXzJRVs1Y195IIMhk6ppPYUpBHa
            y2ZZOzbMBs5g6K4Fa9wrF8isG0poRLPFW/ZANZ9tJWW8jyPafRGViw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zkftm4fhsuv4gscxwqrxp5jfkhr7u63wsxdehhw0w0cd4kutzy9szzrhy9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5eG41azZMRzc2VHBxbjdo
            RVNPYjFRVkpJM2loL1FaM3Q0WjJFblVDWjFZCkJIaTJrYzB2anh6UFRVWVlMc2s4
            a2h3MGhTbEhUMUJncDF6bTEyd3NBdzQKLS0tIDZRY0JMTDBJbHZoRUY3Q2d4UnZa
            R3h5M09uclRYL3Q2TFBhNllMZWY2M00KTM3/uLPu8g5B4892kC2F1kR0m+WoScc7
            VJhIigWYAuboPRgH1eVfU8959aT3JCZeKinzlXs0EyAdDBDZwqi99g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ms8xr24y5yy0s2se255v8vy2s602twyjqwdlswq0jf50f3ty6cjsuczrev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrNCtVb1h0cFpISlQ5MUVj
            RzNlWjAzTTlEMDlzaVZjMFVUSlM1S1ZHUzBJCkVMQkxXTCsrUmU3N3d2eUUzbzBa
            WGxUY3hIQ3pyVUhrelVZaDVZYUJORzAKLS0tIGxzRUpaTFhiMzhqWm5DUFJMRUpJ
            WWdkMHcwdlA4c3hJZnUwOHVNYXpCa3cKnn41rmhySGCK1YvUHwat45oFiIIjW1SB
            anMLx8UDAI3tKwT0w7fLd/i6faWeJGWbrVHyr6/Htm7GpCgkpvxcfw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-04T18:05:00Z"
    mac: ENC[AES256_GCM,data:vaeBBifQoLaEktWfWp/UNdVREhSpsKJEXl63JZ7VKM5KCC9yRrhzi0s3dz1PGAG4dqpgU4xI0GH0ECmvERwD7Kp0hdVMyLChm2+1oorVJx8vllnVnYZwybop1y7jXpKIq50O91qPxpNfxhwE7ggko33bUnEuwGpdKwd6C2B1Td8=,iv:hYTFifIUtb2ZLDfUMktRS5JStjY1dUjm+PLv2DSgV7A=,tag:WGnZvkhJNawlGlxs+dGeqQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
