network.env: ENC[AES256_GCM,data:AcMe0twnNhfckFuqI4iDjAJrSSaUaeYBQOMq3yN2GI1kQSmGyNQAWpfjJx+aAONafi9ksQ==,iv:u9YWBE0vR//H3/w8ZkqDqFUVLKFk6zNSM6DxbgYRM4I=,tag:jbqGqFySJxyekCYLp10kUQ==,type:str]
k3s.server.token: ENC[AES256_GCM,data:G4hzdpOymw49GSgLGn3V2gVXL0oGHa9oPI8I0Eip09IgrSsuCkofD3JgnumaaF5R3mkQUxmtHgC7QTeqnYH1Y4pxLkTfO7YpBqqaMLFJL3YCMTRuAwxW+DHYRXuNfU5zNsIVjT2NJbI+PHUFukcb4HgxIr5FUBKg5VfU3SQn6zWnKVVGc532uBPujkD+JTmKtawG0UHKyHOPbdxkIw78F68osAgf/AqYVxQOIwPu7TtS7XNFQJfOUwDeFIy4w5MSL86BnRThrX3PVenzEp5asCL9g9jC+urNIeiN5gccyW3x7SodJBQeOryjUJNt6PUFt+VY8Wgs9AW+i2UAwqTSVAo=,iv:KxRsn3JkGRmR3qHOfRYq8yBy89MtRDlL9KwsGVDLs24=,tag:GSZo1D8jojoX4CVFsSFRyg==,type:str]
k3s.agent.token: ENC[AES256_GCM,data:NfIn7EPapJyqRI//3K1+BXB/W1Uy6emvWJbTd+vYjICajnFVHNJfWXplvltMiEf6/iuRmNigX86febMEDXSLLvSsONIIEBNgxZQ28VkhBDo0qO8Mb/EVO006Ofd9PZFN1uWajBfmv4jF266ZJVk/yt67OsQj6tqM+Dg0O8CuW5qx9oX6NFdrCZwKnzFonNQ0xc3yDQSauJMG5QsqJVz3jdlFqKF1NNMwy9EO6Ylnipl590lxOg5GyGLH9aHMnmU0fTDfCfJAqoGZLn2mc2D9Bdhk0kgwr5CxI+biWDiBcyGjsfTL9F578gbRqOhgLdg4zVXeIdEM1mII5tzbbQBtrdc=,iv:qGTJ/S4gwlXlvzf6UoMDiwePBehjHtWFFfxpf1dErcM=,tag:kfrGgeoB2fWc42snDOY/Yw==,type:str]
adguard:
    adminpw: ENC[AES256_GCM,data:kq3mHokAhCxQvOnTQgWlNoIkdnPRxauiNdYo/3jxaqk=,iv:jkKQahQr4I+JILrPAJy9flfWdKadHllIxPK5GkUA7zw=,tag:5qVAMqkf7/xhVzbtdSmjww==,type:str]
sops:
    age:
        - recipient: age10gzj30y0wv32y040ymu2k2u76eldtry335zg9rk58d54algtp40sjgmrf4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFdTRJTElqYTg3Q1JaVjBU
            NFM0YXhHZzJQL2xXOHRXSnpQM1pOTmg4a3djCnF5dVltWFFkdWQzRHpnYzlQdEJZ
            eldCWFY1Y09vMUlHQ2EzQWVoQXkzZk0KLS0tIGNpelJMenVMZU5UeXQ2eWJxS0dE
            M0g5U3RFcTdzS1ZvWk5IUnY5RXZodjQKFY5RNO8h3vzXVfj0Zlws0aWf/F1ZIomO
            fzM2YCt0INA4vStQ3IDigAA0xOlpaV2qyIXQ2cBDbfOC4GyMKUyn9A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zkftm4fhsuv4gscxwqrxp5jfkhr7u63wsxdehhw0w0cd4kutzy9szzrhy9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkZnJWcjFLK2xxOTBhWWl0
            WE9rczA0L1kwSDBYbFVqbDdaTmtKWFFVbzFrCnJOOEJ4QUl2KzFiMjVwYVdBZTk0
            ZGh3VnFGRlNSRzF3Tm1aM0M3elRkSTgKLS0tIG42ZmdmRWhvUUlCcjd5eDBnR2ZT
            eGl3Zk1xRXZoVHdjYWt4N1dnek9vUXMKdksgeMzQIXu3Pkeh+EeaIBdGCetisEpI
            FcunIuStExPdP23YlkliwUyxVLIbwdcRjxETg4Yb4/Rhjp5GrEanFQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ms8xr24y5yy0s2se255v8vy2s602twyjqwdlswq0jf50f3ty6cjsuczrev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxNGpRTWFYaDJocGR2d0Nh
            M0M4cDA0SnNweUVpUjk2NXNIVDJ0Y1AyYzI0CjRSOXlrUml5NS9ySEN0UDZ0cWxt
            VjJHTitjUVlTVlRFOGgxYWYwcUlRbDAKLS0tIEVCK2haQUw2NVM1OUdCU2RaNDg2
            djd0NCtIanVhQVNFb0JVdy9qNUlSU3cKnLLV4FhA6ghBtfAiriTxEhiq0MB2fQbY
            Qrn/adxLjVeV9tq+Xn2OzG90bJwgiS7gI8ap3+AAieeTHQP7BMoP/Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jck0p00460dyqnvsns20pz0xg7ecu0eg2amtqlvtd88jypl47cfq23sjwv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBubWFwVzBHaHpCTm1mRlJF
            cE5OUUZGQk9KRmhnSTI1ZGRHSVpnMFIzUXc0CmM4T3Z2TUJrZzRVUHVRRkVwYy9M
            NDB4Sk1OTm5yL2RVNnRWdjl4eUxqNG8KLS0tIHdPNk0vcmRhNmdkYkxoRWNETGZE
            Uk1tMEkrdTZsWjhnWWg3cHFsSE1DK1UKyf1pOogEXxSD2JSFnytjLYoRghOddPLu
            jfwvCNfzdAHCNtDtkaLtw68Ho3CZ7BA43HClM7l1kIMNu1mwVc8ilg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1w8f4ajl5mgvlncq3tplmlv0f4q8kqz9rrq3yej6g94saeu6jpelqggl23m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5dE1mNGpkOFFNTDdHcllZ
            cGZ3YWtmUXRKUGVRcjAvWHdUZ3lyd0dvV0hJCm5vSUNYekl0ZlFWNDZLY0Era1Vz
            RURqWVZoT1JJcFRLMjFRMDdKdFNUQm8KLS0tIGFMT29sUDZZWmhZRk45aUFpTVlS
            Um5GR2FvR3VoNzNkaTB6REUweFY0NEkKLGknXnb2JcF7FjNd98StYmOdGstE0bLG
            7Q16l47bcDogGZfcuZpzp5JXi38GJxT/2auzoKHiCT37/TY7WKS6ew==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jg4c287extrgkhph23zd3gfzf09ldxqdnaraj9n7rgm28neggs6stggz9l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyTFVxMjBRa1hzUzhoRi9o
            MlJHSUNjMEdVWnUwMVpBeXZSeTJLSFN2UndnCkVlTytRMnFrZEgvNTQwMGlqWFE5
            b3BVcGszRzVEMU5ITjhrY1pQeE1VWm8KLS0tIDN4eDM5RGdrT3A1NlROeWF1amUx
            YWUrTVJPU3VrMk5DTUo3REhtakY4UVEKzh/M81XhiBIsTnuqKqF7f9shBiY1ZIJP
            boUt7kVBRctqp2Yqg7nCal2RJQYFWXY39klz7KrptEc9jblHX3iLHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-27T10:39:21Z"
    mac: ENC[AES256_GCM,data:hFaeBmVnF8Xmte1rivVfjG62G1ZAJ4amjTBqMz/7uVAy9DX3yIhCvt4I8U9A9wzFiLKC/zBuP1RAe7q0sde+g2s24MZGnttc0dagSUawR0yvvX9uH9eCkhduuwdWbZV7pQ+1ZJCbOw5moRnkk43uEdnyFvtFQIozBGUIprWHUfI=,iv:o9pODNqOG6WcPIBdxYur9WS3qWuPVeV0PnKbFP0Cv/U=,tag:+qcwSLdtwrXxdWaVQsFTZw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
