network.env: ENC[AES256_GCM,data:AcMe0twnNhfckFuqI4iDjAJrSSaUaeYBQOMq3yN2GI1kQSmGyNQAWpfjJx+aAONafi9ksQ==,iv:u9YWBE0vR//H3/w8ZkqDqFUVLKFk6zNSM6DxbgYRM4I=,tag:jbqGqFySJxyekCYLp10kUQ==,type:str]
k3s.server.token: ENC[AES256_GCM,data:G4hzdpOymw49GSgLGn3V2gVXL0oGHa9oPI8I0Eip09IgrSsuCkofD3JgnumaaF5R3mkQUxmtHgC7QTeqnYH1Y4pxLkTfO7YpBqqaMLFJL3YCMTRuAwxW+DHYRXuNfU5zNsIVjT2NJbI+PHUFukcb4HgxIr5FUBKg5VfU3SQn6zWnKVVGc532uBPujkD+JTmKtawG0UHKyHOPbdxkIw78F68osAgf/AqYVxQOIwPu7TtS7XNFQJfOUwDeFIy4w5MSL86BnRThrX3PVenzEp5asCL9g9jC+urNIeiN5gccyW3x7SodJBQeOryjUJNt6PUFt+VY8Wgs9AW+i2UAwqTSVAo=,iv:KxRsn3JkGRmR3qHOfRYq8yBy89MtRDlL9KwsGVDLs24=,tag:GSZo1D8jojoX4CVFsSFRyg==,type:str]
k3s.agent.token: ENC[AES256_GCM,data:NfIn7EPapJyqRI//3K1+BXB/W1Uy6emvWJbTd+vYjICajnFVHNJfWXplvltMiEf6/iuRmNigX86febMEDXSLLvSsONIIEBNgxZQ28VkhBDo0qO8Mb/EVO006Ofd9PZFN1uWajBfmv4jF266ZJVk/yt67OsQj6tqM+Dg0O8CuW5qx9oX6NFdrCZwKnzFonNQ0xc3yDQSauJMG5QsqJVz3jdlFqKF1NNMwy9EO6Ylnipl590lxOg5GyGLH9aHMnmU0fTDfCfJAqoGZLn2mc2D9Bdhk0kgwr5CxI+biWDiBcyGjsfTL9F578gbRqOhgLdg4zVXeIdEM1mII5tzbbQBtrdc=,iv:qGTJ/S4gwlXlvzf6UoMDiwePBehjHtWFFfxpf1dErcM=,tag:kfrGgeoB2fWc42snDOY/Yw==,type:str]
sops:
    age:
        - recipient: age10gzj30y0wv32y040ymu2k2u76eldtry335zg9rk58d54algtp40sjgmrf4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5aWp4QkRHV1BlS0JCV2xw
            NGdOZWx5ZmU2TkU4SVFuZlFLYUtoL0JuQnlrCmpXdXRXUWcyUk5CL242dVJDTHMw
            UittYlZmZ05qTlFDUUVEWXdGZ3FNencKLS0tIFhKdXNKZjZWVjZJeEtwZHJGcHpx
            dUNpUUhEd0JMSDRiOEo0Q3VGOWoyQU0KfgZBLx/VTuQp9qe7Pr4VU9vOqBNlzeOJ
            vPEekXdTgnacrTZhRdi/lXyJLPxYGxi3gLGBwWvhkREXdT+5Yr/SnQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zkftm4fhsuv4gscxwqrxp5jfkhr7u63wsxdehhw0w0cd4kutzy9szzrhy9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBZzE0SUN2eGxVSW0xOUlu
            aldJU0I4OGkzZmIzRG12dzB0OTFEK1pwbXpzCnB0QWIxZjR3Z01SM3llc0tEcmFa
            eUdqMjN0bjJpT3ZxMXBHeXBqMm91VW8KLS0tIFNNT3BVaU1SODZqbnFseFExeHBD
            VDNyYktHcHZVelRPL1R0bEN0L1lpYmMKjP9qZTwXqzBBfUCPIaUJ7z3TIUetBRMy
            TwI62Nhnc5cobULNGXarGFq24b5vWB4MPHiKwliefBl20uaP8dB3cQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-04T18:05:00Z"
    mac: ENC[AES256_GCM,data:vaeBBifQoLaEktWfWp/UNdVREhSpsKJEXl63JZ7VKM5KCC9yRrhzi0s3dz1PGAG4dqpgU4xI0GH0ECmvERwD7Kp0hdVMyLChm2+1oorVJx8vllnVnYZwybop1y7jXpKIq50O91qPxpNfxhwE7ggko33bUnEuwGpdKwd6C2B1Td8=,iv:hYTFifIUtb2ZLDfUMktRS5JStjY1dUjm+PLv2DSgV7A=,tag:WGnZvkhJNawlGlxs+dGeqQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
