---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: monitoring
  namespace: monitoring
spec:
  interval: 15m
  timeout: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 87.19.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: monitoring
  releaseName: observability
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    crds:
      enabled: true
    
    kubeControllerManager:
      enabled: false
    kubeScheduler:
      enabled: false
    kubeEtcd:
      enabled: false
    kubeProxy:
      enabled: false

    prometheus:
      prometheusSpec:
        storageSpec:
          volumeClaimTemplate:
            spec:
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 10Gi

    grafana:
      persistence:
        enabled: true
        size: 2Gi

      ingress:
        enabled: true
        ingressClassName: traefik
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
        hosts:
          - grafana.schweigert.io
        path: /
        pathType: Prefix
        tls:
          - secretName: grafana-tls
            hosts:
              - grafana.schweigert.io