apiVersion: v1
kind: Secret
metadata:
    name: grafana
    namespace: monitoring
type: Opaque
stringData:
    admin_username: ENC[AES256_GCM,data:jcy6UWJuc8yH,iv:PwSLl8ZpzSQ2IRH/rviOFY7JhYO1CeROtp5Bp/GI3/4=,tag:yLYIzrSZyu/NDbkqNmDqKQ==,type:str]
    admin_password: ENC[AES256_GCM,data:9iuiyAL4xCJuoYh20CCKfQ4uTkuSd77GM7+Non9zNoU=,iv:FFKaCSe4a3tjPYmE7u2RKhvpJWvErKIX8vVcmcWCxbQ=,tag:vkTaCzIeMDc0fTl7vEnE6Q==,type:str]
sops:
    age:
        - recipient: age10gzj30y0wv32y040ymu2k2u76eldtry335zg9rk58d54algtp40sjgmrf4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNTkMvcnU3a3RFYU9TeFdj
            VXVFRWExQXNrODVJNEFES1hVYVZvaC9XSUdFCjBpTUxJUEkxR0V3eENiQjFqTVRN
            NmlnVzJlTGxYVkpFWWVvSFdHNlNiTXMKLS0tIFNoYTVlUkVxZVZYTnRmaTZuMUJm
            REM5d1VCOEw2Y0szdW1mamozRTkvZEkK0zdQNXS4jH0Yh/rC0QrO/vOpImhObcH3
            +aBJqI5L65PPGle3kaEn/R+G0VihFTUXKPnNYJkRoX4eWbAQ8bjbjA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-22T17:28:19Z"
    mac: ENC[AES256_GCM,data:tSLPscJrtjz1IEEGeXgSLODYaTwQuZgQHvR2mri80zIRUKyoNovTSj/kRsJiCNRFJbrRl9ZK8OLltgrc7I3iCNTMTUuYLuB9xi7nzpNxKrjqyySDbyegkFoW0OsMI5j6ipRHZ3s6guHEajwzf5GfWdghLy7ylvOppe766Y2OHOE=,iv:hze5Tlgok+9pb6XLulOWGbhV/L3JThm5QjavOBcte1U=,tag:I4+Imkk3vjvPMSIyhYfWig==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
