---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-media
spec:
  capacity:
    storage: 1Ti
  accessModes: [ReadOnlyMany]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions: [nfsvers=4.2, hard, noatime]
  nfs:
    server: ${NFS_HOST}
    path: /tank/media
    readOnly: true
  claimRef:
    namespace: jellyfin
    name: jellyfin-media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-media
  namespace: jellyfin
spec:
  storageClassName: ""
  volumeName: jellyfin-media
  accessModes: [ReadOnlyMany]
  resources:
    requests:
      storage: 1Ti
