---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  interval: 1h
  timeout: 5m
  chart:
    spec:
      chart: home-assistant
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: pajikos
        namespace: home-assistant
  releaseName: home-assistant
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    service:
      type: ClusterIP
      port: 8123
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 5Gi
      storageClass: ""
    ingress:
      enabled: true
      className: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-staging
      hosts:
        - paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: home-assistant-tls
          hosts:
            - schweigert.io
    configuration:
      enabled: true
      forceInit: true
      trusted_proxies:
      - 10.0.0.0/8
