---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-config
  namespace: gluetun
spec:
  storageClassName: nfs-tank
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi
