apiVersion: v1
kind: Secret
metadata:
    name: gluetun
    namespace: gluetun
type: Opaque
stringData:
    wireguard_private_key: ENC[AES256_GCM,data:BETBeo0eheNsPmYyiuhYDBrdbCTTuXMS8qudh/fqa+aEXuPSs7APTMzPoB4=,iv:E4KgboPrGd0zhQAnOVcZKh/1gfskY/sEXi/W8qVOTs4=,tag:i9w9VCWrZ1xSTJk/ODnR5A==,type:str]
    wireguard_addresses: ENC[AES256_GCM,data:bhhD0xoAO35y/9y+saGeqQ==,iv:N3RD13qE3468kqSrQPrDx4yKNtQdnD4A03uyrUF6ugA=,tag:GZ3YP771G9OvTcIoCBBweQ==,type:str]
    server_cities: ENC[AES256_GCM,data:yiiL48K33Epx,iv:s7mVKSTGY5vM1UqLkmLH5yX9PrhPHtE6vxqY8E/VYr8=,tag:BtxaFRtpbkSvlcshcd5D8g==,type:str]
sops:
    age:
        - recipient: age10gzj30y0wv32y040ymu2k2u76eldtry335zg9rk58d54algtp40sjgmrf4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqcStnNWFudnpOS29DY3hB
            UzRKbW91SXp2MTZ3cFU5dzVVWGxSSnAyZ1NnCnpVRENmeEx4b3g5MlNnZVJsenJ1
            U0xpbW51SUdoQmxZM3VTMkpXQmNYWk0KLS0tIDRleWhMbTg0VjVaYWx2YXg2aUFL
            Tm1BVGZ5RVhJOVhKQ1R5cTBDMFd2eVEKYWREAVHdbBQbwUagjD4YBr2vHvlcSxB4
            OBfUZk53UqaTF2CGgK0oyK63ec+Aa+rdWUMsN3u2v06uMk7ZWzu0gQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-09T11:37:35Z"
    mac: ENC[AES256_GCM,data:J2ryTheW7wTFW7UnX0U0NMEfQNfikirPIoK17ptLYWD8a2gsIFLaymiIadPuIn6mI288aScooC3/Tk4NsQJ2YKotTL90FpDxnY+qNOpcqQJTO/nO9o4J3NAulHPtMah1ZG7AnMUMYQGZDhfoScb3blg04xAxzUPQjbjmH3Fnx/U=,iv:3+n2nqJuXaWtNijq18F8gRDwVj8M4jd1fVwPtrG4dac=,tag:enwctMF8sL8WsoAFeYBtAw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
