apiVersion: v1
kind: Secret
metadata:
    name: gluetun
    namespace: gluetun
type: Opaque
stringData:
    wireguard_private_key: ENC[AES256_GCM,data:BETBeo0eheNsPmYyiuhYDBrdbCTTuXMS8qudh/fqa+aEXuPSs7APTMzPoB4=,iv:E4KgboPrGd0zhQAnOVcZKh/1gfskY/sEXi/W8qVOTs4=,tag:i9w9VCWrZ1xSTJk/ODnR5A==,type:str]
    wireguard_addresses: ENC[AES256_GCM,data:bhhD0xoAO35y/9y+saGeqQ==,iv:N3RD13qE3468kqSrQPrDx4yKNtQdnD4A03uyrUF6ugA=,tag:GZ3YP771G9OvTcIoCBBweQ==,type:str]
    server_cities: ENC[AES256_GCM,data:yiiL48K33Epx,iv:s7mVKSTGY5vM1UqLkmLH5yX9PrhPHtE6vxqY8E/VYr8=,tag:BtxaFRtpbkSvlcshcd5D8g==,type:str]
sops:
    age:
        - recipient: age10gzj30y0wv32y040ymu2k2u76eldtry335zg9rk58d54algtp40sjgmrf4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqcStnNWFudnpOS29DY3hB
            UzRKbW91SXp2MTZ3cFU5dzVVWGxSSnAyZ1NnCnpVRENmeEx4b3g5MlNnZVJsenJ1
            U0xpbW51SUdoQmxZM3VTMkpXQmNYWk0KLS0tIDRleWhMbTg0VjVaYWx2YXg2aUFL
            Tm1BVGZ5RVhJOVhKQ1R5cTBDMFd2eVEKYWREAVHdbBQbwUagjD4YBr2vHvlcSxB4
            OBfUZk53UqaTF2CGgK0oyK63ec+Aa+rdWUMsN3u2v06uMk7ZWzu0gQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-08T15:24:41Z"
    mac: ENC[AES256_GCM,data:T+vl1Zys0X3uOJvTHFuiSgSZCWWGyMUju1YXbMCtMb8wFg3LXDWA1wFLfxDMMnGKZpe3kzEUba03IynF+3zdsQtj90CxakgVsAIgj/6IIof5o1KWiYGy5DAhQAl9Zw0q0vKfvetDYCXpgGZCJ0ehihFgnivfk46p8797x64lA+Y=,iv:9NLWCb/IJvMvj1HjTecSlRc2AkZ4HOwqrsh7E/ORlOY=,tag:fbdw0979ctLV4kf+wGYtkA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
