network.env: ENC[AES256_GCM,data:AcMe0twnNhfckFuqI4iDjAJrSSaUaeYBQOMq3yN2GI1kQSmGyNQAWpfjJx+aAONafi9ksQ==,iv:u9YWBE0vR//H3/w8ZkqDqFUVLKFk6zNSM6DxbgYRM4I=,tag:jbqGqFySJxyekCYLp10kUQ==,type:str]
sops:
    age:
        - recipient: age10gzj30y0wv32y040ymu2k2u76eldtry335zg9rk58d54algtp40sjgmrf4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5aWp4QkRHV1BlS0JCV2xw
            NGdOZWx5ZmU2TkU4SVFuZlFLYUtoL0JuQnlrCmpXdXRXUWcyUk5CL242dVJDTHMw
            UittYlZmZ05qTlFDUUVEWXdGZ3FNencKLS0tIFhKdXNKZjZWVjZJeEtwZHJGcHpx
            dUNpUUhEd0JMSDRiOEo0Q3VGOWoyQU0KfgZBLx/VTuQp9qe7Pr4VU9vOqBNlzeOJ
            vPEekXdTgnacrTZhRdi/lXyJLPxYGxi3gLGBwWvhkREXdT+5Yr/SnQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zkftm4fhsuv4gscxwqrxp5jfkhr7u63wsxdehhw0w0cd4kutzy9szzrhy9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBZzE0SUN2eGxVSW0xOUlu
            aldJU0I4OGkzZmIzRG12dzB0OTFEK1pwbXpzCnB0QWIxZjR3Z01SM3llc0tEcmFa
            eUdqMjN0bjJpT3ZxMXBHeXBqMm91VW8KLS0tIFNNT3BVaU1SODZqbnFseFExeHBD
            VDNyYktHcHZVelRPL1R0bEN0L1lpYmMKjP9qZTwXqzBBfUCPIaUJ7z3TIUetBRMy
            TwI62Nhnc5cobULNGXarGFq24b5vWB4MPHiKwliefBl20uaP8dB3cQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-03T18:59:42Z"
    mac: ENC[AES256_GCM,data:h13tkbq1QVq08jaYqwLR2048oZweAny4A1ByUn+29b5OHttPDzjWhjX6Z2PyuxqKNt4IEYE2HHt1kSiPrCJB7EFlPVddYKfKJO0HXJJrAcqfPft2pA+bD9kAddZca+NAXFdAN8Ep16qJNbn62Z0Yk9ICKMMXH7VEObLNlUINzjA=,iv:S3Bn5+YkIx/o3G9qOu+YTBxYzO+mJsVXh+Vd5NK4W2w=,tag:BTqyYg+OsS41hR1fDxJUcg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
